Config = {}
Config.Locale = 'en'

Config.SilentWeapons = {
	["WEAPON_PISTOL"] = "COMPONENT_AT_PI_SUPP_02",
	["WEAPON_PISTOL50"] = "COMPONENT_AT_AR_SUPP_02",
	["WEAPON_COMBATPISTOL"] = "COMPONENT_AT_PI_SUPP",
	["WEAPON_APPISTOL"] = "COMPONENT_AT_PI_SUPP",
	["WEAPON_HEAVYPISTOL"] = "COMPONENT_AT_PI_SUPP",
	["WEAPON_VINTAGEPISTOL"] = "COMPONENT_AT_PI_SUPP",
	["WEAPON_SMG"] = "COMPONENT_AT_PI_SUPP",
	["WEAPON_MICROSMG"] = "COMPONENT_AT_AR_SUPP_02",
	["WEAPON_ASSAULTSMG"] = "COMPONENT_AT_AR_SUPP_02",
	["WEAPON_ASSAULTRIFLE"] = "COMPONENT_AT_AR_SUPP_02",
	["WEAPON_CARBINERIFLE"] = "COMPONENT_AT_AR_SUPP",
	["WEAPON_ADVANCEDRIFLE"] = "COMPONENT_AT_AR_SUPP",
	["WEAPON_SPECIALCARBINE"] = "COMPONENT_AT_AR_SUPP_02",
	["WEAPON_BULLPUPRIFLE"] = "COMPONENT_AT_AR_SUPP",
	["WEAPON_ASSAULTSHOTGUN"] = "COMPONENT_AT_AR_SUPP",
	["WEAPON_HEAVYSHOTGUN"] = "COMPONENT_AT_AR_SUPP_02",
	["WEAPON_BULLPUPSHOTGUN"] = "COMPONENT_AT_AR_SUPP_02",
	["WEAPON_PUMPSHOTGUN"] = "COMPONENT_AT_SR_SUPP",
	["WEAPON_MARKSMANRIFLE"] = "COMPONENT_AT_AR_SUPP",
	["WEAPON_SNIPERRIFLE"] = "COMPONENT_AT_AR_SUPP_02",
	["WEAPON_MACHINEPISTOL"] = "COMPONENT_AT_PI_SUPP",
}

Config.FlashLightWeapons = {
	["WEAPON_PISTOL"] = "COMPONENT_AT_PI_FLSH",
	["WEAPON_PISTOL50"] = "COMPONENT_AT_PI_FLSH",
	["WEAPON_COMBATPISTOL"] = "COMPONENT_AT_PI_FLSH",
	["WEAPON_APPISTOL"] = "COMPONENT_AT_PI_FLSH",
	["WEAPON_HEAVYPISTOL"] = "COMPONENT_AT_PI_FLSH",
	["WEAPON_SMG"] = "COMPONENT_AT_AR_FLSH",
	["WEAPON_MICROSMG"] = "COMPONENT_AT_PI_FLSH",
	["WEAPON_ASSAULTSMG"] = "COMPONENT_AT_AR_FLSH",
	["WEAPON_COMBATPDW"] = "COMPONENT_AT_AR_FLSH",
	["WEAPON_ASSAULTRIFLE"] = "COMPONENT_AT_AR_FLSH",
	["WEAPON_CARBINERIFLE"] = "COMPONENT_AT_AR_FLSH",
	["WEAPON_ADVANCEDRIFLE"] = "COMPONENT_AT_AR_FLSH",
	["WEAPON_SPECIALCARBINE"] = "COMPONENT_AT_AR_FLSH",
	["WEAPON_BULLPUPRIFLE"] = "COMPONENT_AT_AR_FLSH",
	["WEAPON_ASSAULTSHOTGUN"] = "COMPONENT_AT_AR_FLSH",
	["WEAPON_HEAVYSHOTGUN"] = "COMPONENT_AT_AR_FLSH",
	["WEAPON_BULLPUPSHOTGUN"] = "COMPONENT_AT_AR_FLSH",
	["WEAPON_PUMPSHOTGUN"] = "COMPONENT_AT_AR_FLSH",
	["WEAPON_MARKSMANRIFLE"] = "COMPONENT_AT_AR_FLSH",
}

Config.GripWeapons = {
	["WEAPON_COMBATPDW"] = "COMPONENT_AT_AR_AFGRIP",
	["WEAPON_ASSAULTRIFLE"] = "COMPONENT_AT_AR_AFGRIP",
	["WEAPON_CARBINERIFLE"] = "COMPONENT_AT_AR_AFGRIP",
	["WEAPON_SPECIALCARBINE"] = "COMPONENT_AT_AR_AFGRIP",
	["WEAPON_BULLPUPRIFLE"] = "COMPONENT_AT_AR_AFGRIP",
	["WEAPON_ASSAULTSHOTGUN"] = "COMPONENT_AT_AR_AFGRIP",
	["WEAPON_HEAVYSHOTGUN"] = "COMPONENT_AT_AR_AFGRIP",
	["WEAPON_BULLPUPSHOTGUN"] = "COMPONENT_AT_AR_AFGRIP",
	["WEAPON_MARKSMANRIFLE"] = "COMPONENT_AT_AR_AFGRIP",
}

Config.ExtendedMagazineWeapons = {
	["WEAPON_PISTOL"] = "COMPONENT_PISTOL_CLIP_02",
	["WEAPON_PISTOL50"] = "COMPONENT_PISTOL50_CLIP_02",
	["WEAPON_COMBATPISTOL"] = "COMPONENT_COMBATPISTOL_CLIP_02",
	["WEAPON_APPISTOL"] = "COMPONENT_APPISTOL_CLIP_02",
	["WEAPON_SNSPISTOL"] = "COMPONENT_SNSPISTOL_CLIP_02",
	["WEAPON_HEAVYPISTOL"] = "COMPONENT_HEAVYPISTOL_CLIP_02",
	["WEAPON_VINTAGEPISTOL"] = "COMPONENT_VINTAGEPISTOL_CLIP_02",
	["WEAPON_SMG"] = "COMPONENT_SMG_CLIP_02",
	["WEAPON_MICROSMG"] = "COMPONENT_MICROSMG_CLIP_02",
	["WEAPON_ASSAULTSMG"] = "COMPONENT_ASSAULTSMG_CLIP_02",
	["WEAPON_COMBATPDW"] = "COMPONENT_COMBATPDW_CLIP_02",
	["WEAPON_ASSAULTRIFLE"] = "COMPONENT_ASSAULTRIFLE_CLIP_02",
	["WEAPON_CARBINERIFLE"] = "COMPONENT_CARBINERIFLE_CLIP_02",
	["WEAPON_ADVANCEDRIFLE"] = "COMPONENT_ADVANCEDRIFLE_CLIP_02",
	["WEAPON_SPECIALCARBINE"] = "COMPONENT_SPECIALCARBINE_CLIP_02",
	["WEAPON_BULLPUPRIFLE"] = "COMPONENT_BULLPUPRIFLE_CLIP_02",
	["WEAPON_COMPACTRIFLE"] = "COMPONENT_COMPACTRIFLE_CLIP_02",
	["WEAPON_MACHINEPISTOL"] = "COMPONENT_MACHINEPISTOL_CLIP_02",
	["WEAPON_HEAVYSHOTGUN"] = "COMPONENT_HEAVYSHOTGUN_CLIP_02",
	["WEAPON_GUSENBERG"] = "COMPONENT_GUSENBERG_CLIP_02",
}

Config.VeryExtendedMagazineWeapons = {
	["WEAPON_SMG"] = "COMPONENT_SMG_CLIP_03",
	["WEAPON_COMBATPDW"] = "COMPONENT_COMBATPDW_CLIP_03",
	["WEAPON_ASSAULTRIFLE"] = "COMPONENT_ASSAULTRIFLE_CLIP_03",
	["WEAPON_CARBINERIFLE"] = "COMPONENT_CARBINERIFLE_CLIP_03",
	["WEAPON_SPECIALCARBINE"] = "COMPONENT_SPECIALCARBINE_CLIP_03",
	["WEAPON_COMPACTRIFLE"] = "COMPONENT_COMPACTRIFLE_CLIP_03",
	["WEAPON_MACHINEPISTOL"] = "COMPONENT_MACHINEPISTOL_CLIP_03",
	["WEAPON_HEAVYSHOTGUN"] = "COMPONENT_HEAVYSHOTGUN_CLIP_03",
}

Config.ScopeWeapons = {
	["WEAPON_SMG"] = "COMPONENT_AT_SCOPE_MACRO_02",
	["WEAPON_MICROSMG"]	= "COMPONENT_AT_SCOPE_MACRO",
	["WEAPON_ASSAULTSMG"] = "COMPONENT_AT_SCOPE_MACRO",
	["WEAPON_COMBATPDW"] = "COMPONENT_AT_SCOPE_SMALL",
	["WEAPON_ASSAULTRIFLE"] = "COMPONENT_AT_SCOPE_MACRO",
	["WEAPON_CARBINERIFLE"] = "COMPONENT_AT_SCOPE_MEDIUM",
	["WEAPON_ADVANCEDRIFLE"] = "COMPONENT_AT_SCOPE_SMALL",
	["WEAPON_SPECIALCARBINE"] = "COMPONENT_AT_SCOPE_MEDIUM",
	["WEAPON_BULLPUPRIFLE"] = "COMPONENT_AT_SCOPE_SMALL",
	["WEAPON_SNIPERRIFLE"] = "COMPONENT_AT_SCOPE_LARGE",
	["WEAPON_HEAVYSNIPER"] = "COMPONENT_AT_SCOPE_LARGE",
}

Config.AdvancedScopeWeapons = {
	["WEAPON_SNIPERRIFLE"] = "COMPONENT_AT_SCOPE_MAX",
	["WEAPON_HEAVYSNIPER"] = "COMPONENT_AT_SCOPE_MAX",
}

Config.YusufWeapons = {
	["WEAPON_PISTOL"] = "COMPONENT_PISTOL_VARMOD_LUXE",
	["WEAPON_PISTOL50"] = "COMPONENT_PISTOL50_VARMOD_LUXE",
	["WEAPON_APPISTOL"] = "COMPONENT_APPISTOL_VARMOD_LUXE",
	["WEAPON_HEAVYPISTOL"] = "COMPONENT_HEAVYPISTOL_VARMOD_LUXE",
	["WEAPON_SMG"] = "COMPONENT_SMG_VARMOD_LUXE",
	["WEAPON_MICROSMG"] = "COMPONENT_MICROSMG_VARMOD_LUXE",
	["WEAPON_ASSAULTRIFLE"] = "COMPONENT_ASSAULTRIFLE_VARMOD_LUXE",
	["WEAPON_CARBINERIFLE"] = "COMPONENT_CARBINERIFLE_VARMOD_LUXE",
	["WEAPON_ADVANCEDRIFLE"] = "COMPONENT_ADVANCEDRIFLE_VARMOD_LUXE",
}

Config.LowriderWeapons = {
	["WEAPON_COMBATPISTOL"] = "COMPONENT_COMBATPISTOL_VARMOD_LOWRIDER",
	["WEAPON_SNSPISTOL"] = "COMPONENT_SNSPISTOL_VARMOD_LOWRIDER",
	["WEAPON_ASSAULTSMG"] = "COMPONENT_ASSAULTSMG_VARMOD_LOWRIDER",
	["WEAPON_SPECIALCARBINE"] = "COMPONENT_SPECIALCARBINE_VARMOD_LOWRIDER",
	["WEAPON_BULLPUPRIFLE"] = "COMPONENT_BULLPUPRIFLE_VARMOD_LOWRIDER",
	["WEAPON_PUMPSHOTGUN"] = "COMPONENT_PUMPSHOTGUN_VARMOD_LOWRIDER",
}

Config.WeaponsSkins = {
	["WEAPON_KNUCKLE"] = {
		labels = {
			"WCT_KNUCK_01",
			"WCT_KNUCK_02",
			"WCT_KNUCK_BG",
			"WCT_KNUCK_DLR",
			"WCT_KNUCK_DMD",
			"WCT_KNUCK_HT",
			"WCT_KNUCK_LV",
			"WCT_KNUCK_PC",
			"WCT_KNUCK_SLG",
			"WCT_KNUCK_VG",
		},
		hashes = {
			"COMPONENT_KNUCKLE_VARMOD_BASE",
			"COMPONENT_KNUCKLE_VARMOD_PIMP",
			"COMPONENT_KNUCKLE_VARMOD_BALLAS",
			"COMPONENT_KNUCKLE_VARMOD_DOLLAR",
			"COMPONENT_KNUCKLE_VARMOD_DIAMOND",
			"COMPONENT_KNUCKLE_VARMOD_HATE",
			"COMPONENT_KNUCKLE_VARMOD_LOVE",
			"COMPONENT_KNUCKLE_VARMOD_PLAYER",
			"COMPONENT_KNUCKLE_VARMOD_KING",
			"COMPONENT_KNUCKLE_VARMOD_VAGOS",
		}
	},
	["WEAPON_SWITCHBLADE"] = {
		labels = {
			"WCT_SB_BASE",
			"WCT_SB_VAR1",
			"WCT_SB_VAR2",
		},
		hashes = {
			"COMPONENT_SWITCHBLADE_VARMOD_BASE",
			"COMPONENT_SWITCHBLADE_VARMOD_VAR1",
			"COMPONENT_SWITCHBLADE_VARMOD_VAR2",
		}
	},
}