INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES
	('drill', 'Drill', 1, 0, 1),
	('oxygen_mask', 'Oxygen Mask', -1, 0, 1),
	('bulletproof', 'Bullet-Proof Vest', -1, 0, 1),
	('clip', 'Weapon Clip', -1, 0, 1),
	('grip', 'Grip', -1, 0, 1),
	('flashlight', 'Flashlight', -1, 0, 1),
	('silent', 'Silencer', -1, 0, 1),
	('scope', 'Scope', -1, 0, 1),
	('advanced_scope', 'Advanced Scope', -1, 0, 1),
	('extended_magazine', 'Extended Magazine', -1, 0, 1),
	('very_extended_magazine', 'Very Extended Magazine', -1, 0, 1),
	('yusuf', 'Luxury Skin', -1, 0, 1),
	('lowrider', 'Lowrider Skin', -1, 0, 1),
	('darknet', 'Dark Net', 1, 0, 1)
;

INSERT INTO `shops` (name, item, price) VALUES
	('IllegalShop', 'drill', 1000),
	('IllegalShop', 'blowpipe', 500),
	('IllegalShop', 'darknet', 250),
	('LegalShop', 'fixkit', 750),
	('LegalShop', 'bulletproof', 2500),
	('LegalShop', 'oxygen_mask', 500),
	('LegalShop', 'clip', 5000),
	('LegalShop', 'grip', 100),
	('LegalShop', 'flashlight', 50),
	('LegalShop', 'silent', 250),
	('LegalShop', 'scope', 100),
	('LegalShop', 'advanced_scope', 150),
	('LegalShop', 'extended_magazine', 250),
	('LegalShop', 'very_extended_magazine', 500),
	('LegalShop', 'yusuf', 3000),
	('LegalShop', 'lowrider', 1500),
	('PoliceShop', 'fixkit', 100),
	('PoliceShop', 'bulletproof', 300),
	('PoliceShop', 'oxygen_mask', 250),
	('PoliceShop', 'clip', 500),
	('PoliceShop', 'grip', 50),
	('PoliceShop', 'flashlight', 25),
	('PoliceShop', 'scope', 50),
	('PoliceShop', 'advanced_scope', 100),
	('PoliceShop', 'extended_magazine', 150),
	('PoliceShop', 'very_extended_magazine', 250)
;